/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2017-08-27 02:36:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class add_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <link rel=\"shortcut icon\" href=\"favicon.ico\"> \n");
      out.write("    <link href=\"css/bootstrap.min14ed.css?v=3.3.6\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"css/font-awesome.min93e3.css?v=4.4.0\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"css/plugins/chosen/chosen.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"css/animate.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"css/style.min862f.css?v=4.1.0\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"css/plugins/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body class=\"gray-bg\">\n");
      out.write("    <div class=\"wrapper wrapper-content animated fadeInRight\">\n");
      out.write("        \n");
      out.write("        <div class=\"row\">\n");
      out.write("        \n");
      out.write("            <div class=\"col-sm-12\">\n");
      out.write("                <div class=\"ibox float-e-margins\">\n");
      out.write("                    <div class=\"ibox-title\">\n");
      out.write("                        <h5>添加商品</h5>\n");
      out.write("                        <div class=\"ibox-tools\">\n");
      out.write("                            <a class=\"collapse-link\">\n");
      out.write("                                <i class=\"fa fa-chevron-up\"></i>\n");
      out.write("                            </a>\n");
      out.write("                           \n");
      out.write("                            <a class=\"close-link\">\n");
      out.write("                                <i class=\"fa fa-times\"></i>\n");
      out.write("                            </a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"ibox-content\">\n");
      out.write("                        <form class=\"form-horizontal m-t\" action=\"/com.edu360/AddProduct\" method=\"post\" id=\"signupForm\">\n");
      out.write("                            <div class=\"form-group\">\n");
      out.write("                                <label class=\"col-sm-3 control-label\">商品名称：</label>\n");
      out.write("                                <div class=\"col-sm-4\">\n");
      out.write("                                    <input id=\"name\" name=\"name\" class=\"form-control\" type=\"text\">\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"form-group\">\n");
      out.write("                                <label class=\"col-sm-3 control-label\">商品价格：</label>\n");
      out.write("                                <div class=\"col-sm-4\">\n");
      out.write("                                    <input id=\"price\" name=\"price\" class=\"form-control\" type=\"text\">\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                          \n");
      out.write("                            <div class=\"form-group\">\n");
      out.write("                                <label class=\"col-sm-3 control-label\">类目：</label>\n");
      out.write("                                <div class=\"col-sm-4\">\n");
      out.write("                                    <input id=\"cate\" name=\"category\" class=\"form-control\" type=\"text\">\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("\t\t\t\t\t\t\t                            <div class=\"form-group\">\n");
      out.write("                                <label class=\"col-sm-3 control-label\">数量：</label>\n");
      out.write("                                <div class=\"col-sm-4\">\n");
      out.write("                                    <input id=\"num\" name=\"pnum\" class=\"form-control\" type=\"text\">\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("\t\t\t\t\t\t\t                            <div class=\"form-group\">\n");
      out.write("                                <label class=\"col-sm-3 control-label\">描述：</label>\n");
      out.write("                                <div class=\"col-sm-4\">\n");
      out.write("                                    <input id=\"desc\" name=\"description\" class=\"form-control\" type=\"text\">\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                           \n");
      out.write("                            <div class=\"form-group\">\n");
      out.write("                                <div class=\"col-sm-8 col-sm-offset-3\">\n");
      out.write("                                    <button class=\"btn btn-success\" type=\"submit\"><i class=\"fa fa-save\"></i> &nbsp;&nbsp;添加&nbsp;&nbsp; </button>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </form>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>  \n");
      out.write("    </div>\n");
      out.write("    <script src=\"js/jquery.min.js?v=2.1.4\"></script>\n");
      out.write("    <script src=\"js/bootstrap.min.js?v=3.3.6\"></script>\n");
      out.write("    <script src=\"js/content.min.js?v=1.0.0\"></script>\n");
      out.write("\n");
      out.write("    <script src=\"js/plugins/validate/jquery.validate.min.js\"></script>\n");
      out.write("    <script src=\"js/plugins/validate/messages_zh.min.js\"></script>\n");
      out.write("    <script src=\"js/plugins/chosen/chosen.jquery.js\"></script>\n");
      out.write("    <script src=\"js/demo/form-validate-demo.min.js\"></script>\n");
      out.write("    <script src=\"js/demo/form-advanced-demo.min.js\"></script>\n");
      out.write("\n");
      out.write("    \n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
