/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2017-08-27 02:35:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1503714901000L));
    _jspx_dependants.put("jar:file:/Users/Zd/Desktop/GitHub/BigDataTrain/02JavaWEBEE/train_workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WEB11/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<!-- Mirrored from www.zi-han.net/theme/hplus/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 20 Jan 2016 14:20:37 GMT -->\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta name=\"renderer\" content=\"webkit\">\r\n");
      out.write("    <meta http-equiv=\"Cache-Control\" content=\"no-siteapp\" />\r\n");
      out.write("    <title></title>\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"favicon.ico\">\r\n");
      out.write("    <link href=\"css/bootstrap.min14ed.css?v=3.3.6\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/font-awesome.min93e3.css?v=4.4.0\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/style.min862f.css?v=4.1.0\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"fixed-sidebar full-height-layout gray-bg\" style=\"overflow:hidden\">\r\n");
      out.write("    <div id=\"wrapper\">\r\n");
      out.write("        <!--左侧导航开始-->\r\n");
      out.write("        <nav class=\"navbar-default navbar-static-side\" role=\"navigation\">\r\n");
      out.write("            <div class=\"nav-close\"><i class=\"fa fa-times-circle\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"sidebar-collapse\">\r\n");
      out.write("                <ul class=\"nav\" id=\"side-menu\">\r\n");
      out.write("                    <li class=\"nav-header\">\r\n");
      out.write("                        <div class=\"dropdown profile-element\">\r\n");
      out.write("                            <span><img alt=\"image\" class=\"img-circle\" src=\"img/profile_small.jpg\" /></span>\r\n");
      out.write("                            <a data-toggle=\"dropdown\" class=\"dropdown-toggle\" href=\"#\">\r\n");
      out.write("                                <span class=\"clear\">\r\n");
      out.write("                               <span class=\"block m-t-xs\"><strong class=\"font-bold\">Beaut-zihan</strong></span>\r\n");
      out.write("                                <span class=\"text-muted text-xs block\">超级管理员<b class=\"caret\"></b></span>\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <ul class=\"dropdown-menu animated fadeInRight m-t-xs\">\r\n");
      out.write("                                <li><a class=\"J_menuItem\" href=\"form_avatar.html\">修改头像</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li><a class=\"J_menuItem\" href=\"profile.html\">个人资料</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li><a class=\"J_menuItem\" href=\"contacts.html\">联系我们</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li><a class=\"J_menuItem\" href=\"mailbox.html\">信箱</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"divider\"></li>\r\n");
      out.write("                                <li><a href=\"login.html\">安全退出</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <i class=\"fa fa-home\"></i>\r\n");
      out.write("                            <span class=\"nav-label\">商品管理</span>\r\n");
      out.write("                            <span class=\"fa arrow\"></span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"nav nav-second-level\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a class=\"J_menuItem\" href=\"products.jsp\" data-index=\"0\">查询商品</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a class=\"J_menuItem\" href=\"add.jsp\">添加商品</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a class=\"J_menuItem\" href=\"edit.jsp\">修改商品</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            \r\n");
      out.write("                        </ul>\r\n");
      out.write("\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <!--左侧导航结束-->\r\n");
      out.write("        <!--右侧部分开始-->\r\n");
      out.write("        <div id=\"page-wrapper\" class=\"gray-bg dashbard-1\">\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"row content-tabs\">\r\n");
      out.write("                <button class=\"roll-nav roll-left J_tabLeft\"><i class=\"fa fa-backward\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("                <nav class=\"page-tabs J_menuTabs\">\r\n");
      out.write("                    <div class=\"page-tabs-content\">\r\n");
      out.write("                        <a href=\"javascript:;\" class=\"active J_menuTab\" data-id=\"index_v1.html\">首页</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </nav>\r\n");
      out.write("                <button class=\"roll-nav roll-right J_tabRight\"><i class=\"fa fa-forward\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("                <div class=\"btn-group roll-nav roll-right\">\r\n");
      out.write("                    <button class=\"dropdown J_tabClose\" data-toggle=\"dropdown\">关闭操作<span class=\"caret\"></span>\r\n");
      out.write("\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <ul role=\"menu\" class=\"dropdown-menu dropdown-menu-right\">\r\n");
      out.write("                        <li class=\"J_tabShowActive\"><a>定位当前选项卡</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li class=\"J_tabCloseAll\"><a>关闭全部选项卡</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"J_tabCloseOther\"><a>关闭其他选项卡</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <a href=\"login.html\" class=\"roll-nav roll-right J_tabExit\"><i class=\"fa fa fa-sign-out\"></i> 退出</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row J_mainContent\" id=\"content-main\">\r\n");
      out.write("                <iframe class=\"J_iframe\" name=\"iframe0\" width=\"100%\" height=\"100%\" src=\"index_v148b2.html?v=4.0\" frameborder=\"0\" data-id=\"index_v1.html\" seamless></iframe>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"footer\">\r\n");
      out.write("                <div class=\"pull-right\">&copy; 2016-2017 <a href=\"http://www.edu360.cn/\" target=\"_blank\">学大数据·上小牛学堂</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--右侧部分结束-->\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("    <script src=\"js/jquery.min.js?v=2.1.4\"></script>\r\n");
      out.write("    <script src=\"js/bootstrap.min.js?v=3.3.6\"></script>\r\n");
      out.write("    <script src=\"js/plugins/metisMenu/jquery.metisMenu.js\"></script>\r\n");
      out.write("    <script src=\"js/plugins/slimscroll/jquery.slimscroll.min.js\"></script>\r\n");
      out.write("    <script src=\"js/plugins/layer/layer.min.js\"></script>\r\n");
      out.write("    <script src=\"js/hplus.min.js?v=4.1.0\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/contabs.min.js\"></script>\r\n");
      out.write("    <script src=\"js/plugins/pace/pace.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Mirrored from www.zi-han.net/theme/hplus/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 20 Jan 2016 14:20:37 GMT -->\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
