/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2017-09-27 00:33:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages.commons;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");

request.setAttribute("ctx", request.getContextPath());


      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>修配连汽配市场</title>\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/index.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!--弹出页-->  \r\n");
      out.write("<script type=\"text/javascript\"  src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery.min.js\"></script>      \r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/layer/layer.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    function mygs() {\r\n");
      out.write("        var url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login/toGetPassword.shtml\";\r\n");
      out.write("        $.layer({\r\n");
      out.write("            type: 2,\r\n");
      out.write("\t\t\ttitle: false,//关闭按钮\r\n");
      out.write("            shadeClose: false,\r\n");
      out.write("            shade: [0.6, '#000'],//遮罩\r\n");
      out.write("\t\t\tborder: [0, 0, '#ccc'],//边框\r\n");
      out.write("            area: ['650px', '450px'],//宽高\r\n");
      out.write("            iframe: { src: '' + url + '' },\r\n");
      out.write("\t\t\tshift: [ \"top\" ], //从下面动画弹出\r\n");
      out.write("            end: function () {\r\n");
      out.write("                window.location.reload();\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("           function refreshCode() {\r\n");
      out.write("            document.getElementById('imageValidate').src = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login/Kaptcha.jpg?' + Math.random();\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("                // 如果在框架中，则跳转刷新上级页面\r\n");
      out.write("        if(self.frameElement && self.frameElement.tagName==\"IFRAME\"){\r\n");
      out.write("            parent.location.reload();\r\n");
      out.write("        }\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write(" function login(){\r\n");
      out.write("\t var loginName1=$(\"#loginName\").val();\r\n");
      out.write("\t var password1=$(\"#password\").val();\r\n");
      out.write("\t var validateCode1=$(\"#validateCode\").val();\r\n");
      out.write("\t if(loginName1==''||password1==''||validateCode1==''){\r\n");
      out.write("\t\t $(\"#tips\").html(\"用户名、密码、验证码不能为空\");\r\n");
      out.write("\t }else{\r\n");
      out.write("\t\t $.ajax({\r\n");
      out.write("\t\t\t    type : \"post\",\r\n");
      out.write("\t\t\t\turl :\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login/login.shtml\",\r\n");
      out.write("\t\t\t\tdata:{loginName:loginName1,password:password1,validateCode:validateCode1},\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\tif(data==1){\r\n");
      out.write("\t\t\t\t\t\t $(\"#tips\").html(\"验证码错误\");\r\n");
      out.write("\t\t\t\t\t}else if(data==2){\r\n");
      out.write("\t\t\t\t\t\t $(\"#tips\").html(\"用户名或密码错误\");\r\n");
      out.write("\t\t\t\t\t}else if(data==3){\r\n");
      out.write("\t\t\t\t\t\twindow.location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index/index.shtml\"\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t \r\n");
      out.write("\t }\r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write(" }\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"wid top1\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/logo1.jpg\" /></div>\r\n");
      out.write("    <div class=\"land\">\r\n");
      out.write("    \t<div class=\"wid land_1\">\r\n");
      out.write("        \t<div class=\"title\">\r\n");
      out.write("            \t<ul>\r\n");
      out.write("                \t<li class=\"ziti1\"><a href=\"javascript:;\">xiupeilian.com</a></li>\r\n");
      out.write("                    <li class=\"ziti2\">修配连汽配市场</li>\r\n");
      out.write("                    <li class=\"ziti3\">我的<span>网上汽配店铺</span></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        \t<div class=\"login\">\r\n");
      out.write("        \t<form id=\"loginForm\"  action=\"login.jsp\" method=\"post\">\r\n");
      out.write("            \t<div class=\"login_name\"><input style=\"width:268px;height:38px;font-size:14px;font-family:'微软雅黑';color:#494848;padding-left:13px;border:1px solid #cdcdcd;\" type=\"text\" placeholder=\"用户名/邮箱/手机号\"  id=\"loginName\"/> </div>\r\n");
      out.write("                <div class=\"login_password\"><input type=\"password\" style=\"width:268px;height:38px;font-size:14px;font-family:'微软雅黑';color:#494848;padding-left:13px;border:1px solid #cdcdcd;\" placeholder=\"登陆密码\"  id=\"password\"/></div>\r\n");
      out.write("                <div class=\"login_password\">\r\n");
      out.write("                <input type=\"text\" style=\"width:100px;height:38px;font-size:14px;font-family:'微软雅黑';color:#494848;padding-left:13px;border:1px solid #cdcdcd;\" name=\"validateCode\" id=\"validateCode\" class=\"delValue\"  placeholder=\"验证码\"/>\r\n");
      out.write("                <label for=\"validateCode\" class=\"checkCodePlaceholder\" id=\"checkCodePlaceholder\">看不清</label>\r\n");
      out.write("                <img style=\"height:24px;width:60px;display:inline-block; vertical-align:middle;cursor:pointer;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login/Kaptcha.jpg\" border=\"0\" title=\"看不清,请点击图片换一张\" id=\"imageValidate\" onclick=\"refreshCode()\" >\r\n");
      out.write("               \t<span><a onclick=\"mygs();\" href=\"javascript:;\" style=\"color:red;\">忘记密码？</a></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("        <p style=\"margin-left:100px;margin-top:60px;color:red;font-size:16px\" id=\"tips\"></p>\r\n");
      out.write("       \r\n");
      out.write("             \r\n");
      out.write("                <button class=\"button\" type=\"button\" onclick=\"login()\" >登录</button>\r\n");
      out.write("             </form>\r\n");
      out.write("\t\t\t\t<div class=\"position\">还没有修配连账号吗？赶快<span><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/register/toRegister.shtml\">点击注册</a></span>加入我们吧！</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"clear\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"footer wid\">Copyright © 2014-2024 www.xiupeilian.com  All Rights Reserved. 修配连 版权所有</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
