/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2017-09-27 00:37:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages.staffManage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addStaff_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>修配连汽配市场</title>\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/index.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/validator/style/validator.css\"></link>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/validator/formValidator.js\" type=\"text/javascript\" charset=\"UTF-8\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/validator/formValidatorRegex.js\" type=\"text/javascript\" charset=\"UTF-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t$.formValidator.initConfig({formid:\"registerForm\",onerror:function(msg){},onsuccess:function(){top.jBox.tip(\"正在注册！\",'loading');return true;}});\r\n");
      out.write("\t\r\n");
      out.write("\t//用户名\r\n");
      out.write("\t$(\"#loginName\").formValidator({onshow:\"请输入用户名\",onfocus:\"6-20位字母、数字、下划线组成\",oncorrect:\"该用户名可以注册\"}).inputValidator({min:6,max:20,onerror:\"用户名长度不满足要求\"}).regexValidator({regexp:\"username\",datatype:\"enum\",onerror:\"用户名格式不正确\"})\r\n");
      out.write("\t    .ajaxValidator({\r\n");
      out.write("\t    type : \"post\",\r\n");
      out.write("\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/register/checkLoginName.shtml\",\r\n");
      out.write("\t\tdata:{\"loginName\" : function(){return $(\"#loginName\").val();}},\r\n");
      out.write("\t\tsuccess : function(data){\t\r\n");
      out.write("            if( data == \"1\" )\r\n");
      out.write("\t\t\t{\r\n");
      out.write("                return true;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("            else\r\n");
      out.write("\t\t\t{\r\n");
      out.write("                return false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tbuttons: $(\"#button\"),\r\n");
      out.write("\t\terror: function(){alert(\"服务器没有返回数据，可能服务器忙，请重试\");},\r\n");
      out.write("\t\tonerror : \"此用户名已被注册\",\r\n");
      out.write("\t\tonwait : \"正在对用户名进行合法性校验，请稍候...\"\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//手机号\r\n");
      out.write("\t$(\"#telnum\").formValidator({onshow:\"请输入手机号\",onfocus:\"输入的手机号必须合法\",oncorrect:\"该手机号可以注册\"}).inputValidator({min:11,max:11,onerror:\"手机号码必须是11位的哦\"}).regexValidator({regexp:\"mobile\",datatype:\"enum\",onerror:\"手机号格式不正确\"})\r\n");
      out.write("\t.ajaxValidator({\r\n");
      out.write("\ttype : \"post\",\r\n");
      out.write("\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/register/checkPhone.shtml\",\r\n");
      out.write("\tdata:{\"telnum\" : function(){return $(\"#telnum\").val();}},\r\n");
      out.write("\tsuccess : function(data){\t\r\n");
      out.write("\t    if( data == \"1\" )\r\n");
      out.write("\t\t{\r\n");
      out.write("\t        return true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t    else\r\n");
      out.write("\t\t{\r\n");
      out.write("\t        return false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t},\r\n");
      out.write("\tbuttons: $(\"#button\"),\r\n");
      out.write("\terror: function(){alert(\"服务器没有返回数据，可能服务器忙，请重试\");},\r\n");
      out.write("\tonerror : \"此手机号已被注册\",\r\n");
      out.write("\tonwait : \"正在对手机号进行合法性校验，请稍候...\"\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//邮箱\r\n");
      out.write("\t$(\"#email\").formValidator({onshow:\"请输入邮箱\",onfocus:\"此邮箱用来找回密码\",oncorrect:\"该邮箱可以注册\"}).regexValidator({regexp:\"email\",datatype:\"enum\",onerror:\"邮箱格式不正确\"})\r\n");
      out.write("\t.ajaxValidator({\r\n");
      out.write("\ttype : \"post\",\r\n");
      out.write("\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/register/checkEmail.shtml\",\r\n");
      out.write("\tdata:{\"email\" : function(){return $(\"#email\").val();}},\r\n");
      out.write("\tsuccess : function(data){\t\r\n");
      out.write("\t    if( data == \"1\" )\r\n");
      out.write("\t\t{\r\n");
      out.write("\t        return true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t    else\r\n");
      out.write("\t\t{\r\n");
      out.write("\t        return false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t},\r\n");
      out.write("\tbuttons: $(\"#button\"),\r\n");
      out.write("\terror: function(){alert(\"服务器没有返回数据，可能服务器忙，请重试\");},\r\n");
      out.write("\tonerror : \"此邮箱已被注册\",\r\n");
      out.write("\tonwait : \"正在对邮箱进行合法性校验，请稍候...\"\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#password\").formValidator({onshow:\"请输入密码\",onfocus:\"密码必须为6位以上哦\",oncorrect:\"密码合法\"}).inputValidator({min:6,empty:{leftempty:false,rightempty:false,emptyerror:\"密码两边不能有空符号\"},onerror:\"密码不能为空,请确认\"});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#username\").formValidator({onshow:\"请输入姓名\",onfocus:\"请输入姓名\",oncorrect:\"格式正确\"}).inputValidator({min:2,onerror:\"不能少于2个字符\"});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background: rgba(255,255,255,1);\">\r\n");
      out.write("    <div class=\"pagebody13 wid\" style=\"width:890px;\">\r\n");
      out.write("    \t<div class=\"pagebody13_left\" style=\"\"><h3>汽配商用户管理</h3></div>\r\n");
      out.write("        <div class=\"pagebody13_right\" style=\"width:630px\">\r\n");
      out.write("            <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/staffManage/addStaffManage.shtml\" method=\"post\"  id=\"registerForm\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <h3>新增用户</h3>\r\n");
      out.write("                <li><span>关联号码:</span><input class=\"user\" type=\"text\" placeholder=\"关联号码\" name=\"im\"></li>\r\n");
      out.write("                <li style=\"font-size:14px;color:#999;padding-left:5px;\">如果您没有IM号码，请先 <a style=\"color:#c30d23;\" href=\"\">注册</a></li>\r\n");
      out.write("                <li><span>用户名:</span><input class=\"user\" type=\"text\" placeholder=\"用户名\" name=\"loginName\" id=\"loginName\">  \r\n");
      out.write("                \t<em>*</em>\r\n");
      out.write("                    <i id=\"loginNameTip\" style=\"font-size:14px;font-style:normal;\"></i>\r\n");
      out.write("                </li>\r\n");
      out.write("                 <li><span>手机号:</span><input class=\"user\" type=\"text\" placeholder=\"联系电话\" name=\"phone\" id=\"telnum\">\r\n");
      out.write("\t                 <em>*</em>\r\n");
      out.write("\t                  <i id=\"telnumTip\" style=\"font-size:14px;width:250px;font-style:normal;\"></i>\r\n");
      out.write("                 </li>\r\n");
      out.write("                <li><span>邮箱:</span><input class=\"user\" type=\"text\" placeholder=\"邮箱\" name=\"email\" id=\"email\">\r\n");
      out.write("                \t<em>*</em>\r\n");
      out.write("                     <i id=\"emailTip\" style=\"font-size:14px;width:250px;font-style:normal;\"></i>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li><span>密码:</span><input class=\"user\" type=\"text\" placeholder=\"密码\" name=\"password\" id=\"password\">\r\n");
      out.write("                \t<em>*</em>\r\n");
      out.write("                    <i id=\"passwordTip\" style=\"font-size:14px;width:250px;font-style:normal;\"></i>\r\n");
      out.write("                </li>\r\n");
      out.write("                \r\n");
      out.write("                <li><span>员工姓名:</span><input class=\"user\" type=\"text\" placeholder=\"员工姓名\" name=\"username\" id=\"username\">\r\n");
      out.write("                \t<em>*</em>\r\n");
      out.write("                       <i id=\"usernameTip\" style=\"font-size:14px;width:250px;font-style:normal;\"></i>\r\n");
      out.write("         \t\t</li>\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                <li><span>QQ号码:</span><input class=\"user\" type=\"text\" placeholder=\"QQ号码\" name=\"qq\" id=\"qq\"></li>\r\n");
      out.write("                <li class=\"beizhu\"><span>&nbsp;</span><input type=\"submit\" name=\"button\" id=\"button\" class=\"user1\" value=\"提交\" /></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"clear\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
