/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2017-09-27 00:36:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages.myItems;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addItems_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/Users/Zd/Desktop/GitHub/BigDataTrain/02JavaWEBEE/train_workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/test2_zd_car/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1505531254000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>新增货架</title>\r\n");
      out.write("    <meta name=\"decorator\" content=\"default\"/>\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/index.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/treeTable/jquery.treeTable.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/zTree/js/jquery.ztree.core-3.5.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/zTree/css/zTreeStyle/zTreeStyle.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/treeTable/themes/vsStyle/treeTable.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    <SCRIPT type=\"text/javascript\">\r\n");
      out.write("        var setting = {\r\n");
      out.write("            view: {\r\n");
      out.write("                dblClickExpand: false,\r\n");
      out.write("                selectedMulti:false\r\n");
      out.write("            },\r\n");
      out.write("            data: {\r\n");
      out.write("                simpleData: {\r\n");
      out.write("                    enable: true\r\n");
      out.write("                }\r\n");
      out.write("            },\r\n");
      out.write("            callback: {\r\n");
      out.write("                //beforeClick: beforeClick,\r\n");
      out.write("                onClick: onClick\r\n");
      out.write("            }\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        var zNodes =[\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("]\r\n");
      out.write("\r\n");
      out.write("        function beforeClick(treeId, treeNode) {\r\n");
      out.write("            var check = (treeNode && !treeNode.isParent);\r\n");
      out.write("            if (!check) alert(\"\");\r\n");
      out.write("            return check;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function onClick(e, treeId, treeNode) {\r\n");
      out.write("            var zTree = $.fn.zTree.getZTreeObj(\"menuTree\"),\r\n");
      out.write("                    nodes = zTree.getSelectedNodes(),\r\n");
      out.write("                    v = \"\";\r\n");
      out.write("\r\n");
      out.write("             //alert(nodes[0].name+\" \"+nodes[0].mid);\r\n");
      out.write("           var nName=nodes[0].name;\r\n");
      out.write("             var nId=nodes[0].id;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            nodes.sort(function compare(a,b){return a.id-b.id;});\r\n");
      out.write("            for (var i=0, l=nodes.length; i<l; i++) {\r\n");
      out.write("                v += nodes[i].name + \",\";\r\n");
      out.write("            }\r\n");
      out.write("            if (v.length > 0 ) v = v.substring(0, v.length-1);\r\n");
      out.write("            //cityObj.attr(\"value\", v);\r\n");
      out.write("            var parentMenuObj = $(\"#parentMenuObj\");\r\n");
      out.write("            var parentIdObj = $(\"#parentId\");\r\n");
      out.write("\r\n");
      out.write("            parentMenuObj.val(nName);\r\n");
      out.write("            parentIdObj.val(nId);\r\n");
      out.write("\r\n");
      out.write("            hideMenu();\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function showMenu() {\r\n");
      out.write("            var cityObj = $(\"#parentMenuObj\");\r\n");
      out.write("            var cityOffset = $(\"#parentMenuObj\").offset();\r\n");
      out.write("            $(\"#menuContent\").css({left:cityOffset.left + \"px\", top:cityOffset.top + cityObj.outerHeight() + \"px\"}).slideDown(\"fast\");\r\n");
      out.write("\r\n");
      out.write("            $(\"body\").bind(\"mousedown\", onBodyDown);\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("        function hideMenu() {\r\n");
      out.write("            $(\"#menuContent\").fadeOut(\"fast\");\r\n");
      out.write("            $(\"body\").unbind(\"mousedown\", onBodyDown);\r\n");
      out.write("        }\r\n");
      out.write("        function onBodyDown(event) {\r\n");
      out.write("            if (!(event.target.id == \"menuBtn\" || event.target.id == \"menuContent\" || $(event.target).parents(\"#menuContent\").length>0)) {\r\n");
      out.write("                hideMenu();\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        $(document).ready(function(){\r\n");
      out.write("            var tree=$.fn.zTree.init($(\"#menuTree\"), setting, zNodes);\r\n");
      out.write("            tree.expandAll(true);\r\n");
      out.write("    \r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("         function checkform(){\r\n");
      out.write("            carModelId=$(\"#parentMenuObj\").val();\r\n");
      out.write("            title=$(\"#title\").val();\r\n");
      out.write("\r\n");
      out.write("            if(carModelId.length ==0){\r\n");
      out.write("                alert(\"请选择汽车品牌！\");\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("            if(carPartsId.length == 0){\r\n");
      out.write("                alert(\"请选择配件类别！\");\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("            if(title.length == 0){\r\n");
      out.write("                alert(\"标题不能为空\");\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            return true;\r\n");
      out.write("        }\r\n");
      out.write("    </SCRIPT>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("        ul.ztree {margin-top: 10px;border: 1px solid #617775;background: #f0f6e4;width:220px;height:230px;overflow-y:scroll;overflow-x:auto;}\r\n");
      out.write("        ul.log {border: 1px solid #617775;background: #f0f6e4;width:300px;height:170px;overflow: hidden;}\r\n");
      out.write("        ul.log.small {height:45px;}\r\n");
      out.write("        ul.log li {color: #666666;list-style: none;padding-left: 10px;}\r\n");
      out.write("        ul.log li.dark {background-color: #E3E3E3;}\r\n");
      out.write("\r\n");
      out.write("        #menuEdit td{\r\n");
      out.write("            line-height: 32px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body >\r\n");
      out.write("    \r\n");
      out.write("    <body style=\"background:#efeeec;\">\r\n");
      out.write("<div class=\"pagebody6\" style=\"padding:0px;\">\r\n");
      out.write("        <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/my/addItems.shtml\" enctype=\"multipart/form-data\" method=\"post\" onsubmit=\"return checkform();\">\r\n");
      out.write("        <h1 style=\"font-size:30px;\"><span style=\"margin-left:150px\">新增商品</span></h1>\r\n");
      out.write("        <div class=\"margin1 padding3\"><span>汽车品牌</span>\r\n");
      out.write("                <p style=\"display:inline-block\">\r\n");
      out.write("                                        <span><input type=\"text\" class=\"xinzeng\" id=\"parentMenuObj\" name=\"\" value=\"\" readonly=\"true\" onclick=\"showMenu(); return false;\"></span>\r\n");
      out.write("                                    </p>   <input type=\"hidden\" id=\"parentId\" name=\"brandId\" >\r\n");
      out.write("                                    &nbsp;<a id=\"menuBtn\" style=\"margin-top:4px;\" href=\"#\" onclick=\"showMenu(); return false;\">选择</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"margin1 padding3\"><span>商品标题</span>\r\n");
      out.write("                <input type=\"text\" id=\"title\" class=\"xinzeng\" name=\"title\" />\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"margin1 padding3\"><span>图片路径</span>\r\n");
      out.write("                <input class=\"xinzeng\" type=\"file\" name=\"file\" id=\"button\" value=\"选择上传\" />\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"margin1 padding3\">\r\n");
      out.write("                <span class=\"padding4\">货物描述</span>\r\n");
      out.write("                <textarea id=\"content\" name=\"content\" class=\"miaoshu\"></textarea>\r\n");
      out.write("        </div>\r\n");
      out.write("        <input  type=\"submit\" class=\"tianjia\" value=\"添加到我的货架\" />\r\n");
      out.write("         <div id=\"menuContent\" class=\"menuContent\" style=\"display:none; position: absolute;\">\r\n");
      out.write("                            <ul id=\"menuTree\" class=\"ztree\" style=\"margin-top:0;\"></ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/pages/myItems/addItems.jsp(33,12) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/pages/myItems/addItems.jsp(33,12) '${brandList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${brandList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/pages/myItems/addItems.jsp(33,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("menu");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("{id:\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\", pId:\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu.parentId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\", name:\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu.brandName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"},\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
