/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2017-09-27 00:37:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages.CompanyManage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class companyManage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>修配连汽配市场</title>\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/index.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script language=\"javascript\"> \r\n");
      out.write("function subData(){\r\n");
      out.write(" var zone1=$(\"#zone1\").val();\r\n");
      out.write("var zone2=$(\"#zone2\").val();\r\n");
      out.write("var tel1=$(\"#tel1\").val();\r\n");
      out.write("var tel2=$(\"#tel2\").val();\r\n");
      out.write("\r\n");
      out.write("var cellphone=$(\"#cellphone\").val();\r\n");
      out.write("var qq=$(\"#qq\").val();\r\n");
      out.write("var header=$(\"#header\").val();\r\n");
      out.write("var zoneTel1=$(\"#zone1\").val()+\"-\"+$(\"#tel1\").val();\r\n");
      out.write("var zoneTel2=$(\"#zone2\").val()+\"-\"+$(\"#tel2\").val();\r\n");
      out.write("if(!checkTel()){\r\n");
      out.write("\talert(\"固定电话必须符合格式(区号+座机号)\");\r\n");
      out.write("\treturn;\r\n");
      out.write("}\r\n");
      out.write("if(qq==null || $.trim(qq)==''){\r\n");
      out.write("\talert(\"qq不能为空！\");\r\n");
      out.write("\treturn ;\r\n");
      out.write("}\r\n");
      out.write("if(header==null || $.trim(header)==''){\r\n");
      out.write("\talert(\"负责人不能为空！\");\r\n");
      out.write("\treturn ;\r\n");
      out.write("}\r\n");
      out.write("if(zone1==\"\"&&tel1==\"\"){\r\n");
      out.write("\tzoneTel1=\"\";\r\n");
      out.write("}\r\n");
      out.write("if(zone2==\"\"&&tel2==\"\"){\r\n");
      out.write("\tzoneTel2=\"\";\r\n");
      out.write("} \r\n");
      out.write("$.ajax({\r\n");
      out.write("    url:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/companyAction.do?method=editBusiness\",    //请求的url地址\r\n");
      out.write("    async:true,//请求是否异步，默认为异步，这也是ajax重要特性\r\n");
      out.write("    data:{\"tel1\":zoneTel1,\"tel2\":zoneTel2,\"cellphone\":cellphone,\"qq\":qq,\"header\":header,},    //参数值\r\n");
      out.write("    type:\"post\",   //请求方式\r\n");
      out.write("    success:function(data){\r\n");
      out.write("    \t\tjBox.tip(\"修改成功！\",'success',{timeout:1000});\r\n");
      out.write("    \t   window.location.reload();\r\n");
      out.write("    },\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function cancelData(){\r\n");
      out.write("window.location.reload();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tfunction  addPic(obj) {\r\n");
      out.write("\t\t$.jBox(\"iframe:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/companyManage/addPic.shtml?img=\"+obj, {\r\n");
      out.write("\t\t\ttitle : \"\",\r\n");
      out.write("\t\t\twidth : 500,\r\n");
      out.write("\t\t\theight : 300,\r\n");
      out.write("\t\t\tbuttons : { /*'关闭': true*/}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t} \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    function  updatePic(obj) {\r\n");
      out.write("    \talert(\"qwqw\");\r\n");
      out.write("    \t\t$.jBox(\"iframe:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/companyManage/updatePic.shtml?img=\"+obj, {\r\n");
      out.write("    \t\t\ttitle : \"\",\r\n");
      out.write("    \t\t\twidth : 500,\r\n");
      out.write("    \t\t\theight : 300,\r\n");
      out.write("    \t\t\tbuttons : { /*'关闭': true*/}\r\n");
      out.write("    \t\t});\r\n");
      out.write("    \t} \r\n");
      out.write("    \r\n");
      out.write("    function updateMemo(){\r\n");
      out.write("    var memo=$(\"#memo\").val();\r\n");
      out.write("    $.ajax({\r\n");
      out.write("    url:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/companyAction.do?method=updateMemo\",    //请求的url地址\r\n");
      out.write("    async:true,//请求是否异步，默认为异步，这也是ajax重要特性\r\n");
      out.write("    data:{\"memo\":memo,},    //参数值\r\n");
      out.write("    type:\"post\",   //请求方式\r\n");
      out.write("    success:function(data){\r\n");
      out.write("    \t   window.location.reload();\r\n");
      out.write("    },\r\n");
      out.write("});\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    function checkTel(){\r\n");
      out.write("    \tvar isZone=/^0\\d{2,3}$/;\r\n");
      out.write("        var isPhone = /^\\d{7,8}$/;\r\n");
      out.write("        var tel1=document.getElementById(\"tel1\").value.trim();\r\n");
      out.write("        var tel2=document.getElementById(\"tel2\").value.trim();\r\n");
      out.write("        var zone1=document.getElementById(\"zone1\").value.trim();\r\n");
      out.write("        var zone2=document.getElementById(\"zone2\").value.trim();\r\n");
      out.write("        if(tel1==\"\"&&tel2==\"\"&&zone1==\"\"&&zone2==\"\"){\r\n");
      out.write("        \treturn true;\r\n");
      out.write("        } else{\r\n");
      out.write("    \t    if(isZone.test(zone1)&&isPhone.test(tel1)){\r\n");
      out.write("    \t    \tif((tel2==\"\"&&zone2==\"\")||(isZone.test(zone2)&&isPhone.test(tel2))){\r\n");
      out.write("    \t        return true;\r\n");
      out.write("    \t    \t}else{\r\n");
      out.write("    \t    \t\treturn false;\r\n");
      out.write("    \t    \t}\r\n");
      out.write("    \t    }\r\n");
      out.write("    \t    else{\r\n");
      out.write("    \t    \t  if(isZone.test(zone2)&&isPhone.test(tel2)){\r\n");
      out.write("    \t  \t    \tif((tel1==\"\"&&zone1==\"\")||(isZone.test(zone1)&&isPhone.test(tel1))){\r\n");
      out.write("    \t  \t        \treturn true;\r\n");
      out.write("    \t  \t    \t}else{\r\n");
      out.write("    \t  \t    \t\treturn false;\r\n");
      out.write("    \t  \t    \t}\r\n");
      out.write("    \t  \t    }\r\n");
      out.write("    \t  \t    else{\r\n");
      out.write("    \t  \t        return false;\r\n");
      out.write("    \t  \t    }\r\n");
      out.write("    \t    }\r\n");
      out.write("    \t    }\r\n");
      out.write("        }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"bg_color1 fix\">\r\n");
      out.write("\t\t<!--main颜色-->\r\n");
      out.write("\t\t<div class=\"pagebody1\">\r\n");
      out.write("\t\t\t<div class=\"wid\">\r\n");
      out.write("\t\t\t\t<div class=\"box-yhglzx box-yhglzx2\">\r\n");
      out.write("\t\t\t\t\t<div class=\"box-staman\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tit-z\">\r\n");
      out.write("\t\t\t\t\t\t\t<strong>企业基本信息管理</strong>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<dl class=\"m1\">\r\n");
      out.write("\t\t\t\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t<table class=\"table-z2\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"247\"><strong>企业代码：</strong><span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.companyCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</dt>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t<dl class=\"m1\">\r\n");
      out.write("\t\t\t\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t<table class=\"table-z2\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"247\"><strong>企业名称：</strong><span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.companyName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><strong>企业地址：</strong><span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.address}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</dt>\r\n");
      out.write("\t\t\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t<table class=\"table-z1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"247\"><span>固定电话1：</span><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"zone1\" id=\"zone1\" class=\"txt txt2 \"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.zone1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"width: 30px\" /> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" name=\"tel1\" id=\"tel1\" class=\"txt txt2 \"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.tel1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"width: 70px\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"247\"><span>固定电话2：</span><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"zone2\" id=\"zone2\" class=\"txt txt2 \"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.zone2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"width: 30px\" /> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" name=\"tel2\" id=\"tel2\" class=\"txt txt2 \"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.tel2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"width: 70px\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"213\"><span>手机号：</span><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"cellphone\" id=\"cellphone\" class=\"txt txt2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.phone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><span> QQ：</span><input type=\"text\" name=\"qq\" id=\"qq\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"txt txt2\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.qq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"247\"><span>联系人：</span><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"header\" id=\"header\" class=\"txt txt2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.boss}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t<dl class=\"m1\">\r\n");
      out.write("\t\t\t\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t<table class=\"table-z2\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<c:if test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.manageStyle eq 1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td width=\"247\"><strong>主营：</strong><span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.manageDetail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>（<span style=\"color: red\">*</span>如您需要变更经营范围，请联系客服）\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</c:if>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<c:if test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.manageStyle eq 2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td width=\"247\"><strong>专营：</strong><span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.manageDetail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>（<span style=\"color: red\">*</span>如您需要变更经营范围，请联系客服）\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</c:if>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<c:if test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.manageStyle eq 3}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td width=\"300\"><strong>单项配件：</strong><span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.manageDetail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>（<span style=\"color: red\">*</span>如您需要变更经营范围，请联系客服）\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</c:if>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<c:if test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.manageStyle eq 4 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td width=\"300\"><strong>精品种类：</strong><span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.manageDetail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>（<span style=\"color: red\">*</span>如您需要变更经营范围，请联系客服）\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</c:if>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</dt>\r\n");
      out.write("\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"btn1\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" onclick=\"subData()\">提交</a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"javascript:;\" onclick=\"cancelData()\">取消</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"box-yhglzx box-yhglzx2\" style=\"position: relative;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"box-extpub\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tit-z\">\r\n");
      out.write("\t\t\t\t\t\t\t<strong>企业对外宣传信息管理</strong>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"ul-img-z\">\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a onclick='<c:if test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty company.img1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">addPic(1)</c:if><c:if test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty company.img1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">updatePic(1)</c:if>'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.img1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"sorry\" /></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"txt\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"\">此图片将默认为企业头像</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"img\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/companyManage/<c:if test='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty company.img2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'>addPic.shtml?img=2</c:if>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<c:if test='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty company.img2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'>updatePic.shtml?img=2</c:if>\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.img2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"sorry\" /></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"txt\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"javascript:void(0)\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonclick='<c:if test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty company.img3}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">addPic(3)</c:if><c:if test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty company.img3}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">updatePic(3)</c:if>'><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.img3}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"sorry\" /></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"txt\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<textarea name=\"\" class=\"text\" id=\"memo\" cols=\"30\" rows=\"10\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.description}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"btn\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:void(0)\" onclick=\"updateMemo()\">保存修改</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"phone\">\r\n");
      out.write("\t\t\t\t\t\t\t<textarea name=\"\" class=\"tt1\" id=\"\" readonly=\"readonly\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${company.description}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--中间内容-->\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--main颜色-->\r\n");
      out.write("\t<div class=\"bg_color2\">\r\n");
      out.write("\t\t<!--end底部-->\r\n");
      out.write("\t\t<div class=\"footer wid\">Copyright © 2014-2024 www.xiupeilian.com\r\n");
      out.write("\t\t\tAll Rights Reserved. 修配连 版权所有</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--end底部-->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
